# Generated by Django 3.0.8 on 2020-08-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
