# Generated by Django 3.0.8 on 2020-08-27 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200822_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture2',
            field=models.ImageField(blank=True, default='image/default.jpg', upload_to='image/posts/', verbose_name='画像２'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture3',
            field=models.ImageField(blank=True, default='image/default.jpg', upload_to='image/posts/', verbose_name='画像３'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='image/default.jpg', upload_to='image/posts/', verbose_name='画像１'),
        ),
    ]
